package qupath.ext.quiet.export;

import java.awt.Color;

import static qupath.ext.quiet.export.ScriptGenerator.appendLine;
import static qupath.ext.quiet.export.ScriptGenerator.quote;

/**
 * Generates a self-contained Groovy script documenting a panel / montage
 * export.
 * <p>
 * Panel composition is driven by QuIET's in-memory recipe + composer, which
 * has no compact standalone Groovy equivalent (it depends on the per-category
 * exporters and {@link PanelComposer}). The generated script therefore records
 * the full panel configuration as an editable parameter block and a
 * human-readable description of the recipe, so the export is reproducible and
 * documented even though it is re-run through the QuIET wizard rather than the
 * Script Editor. This mirrors the {@link ScriptGenerator} contract of an
 * editable, self-describing artifact.
 */
final class PanelScriptGenerator {

    private PanelScriptGenerator() {
        // Utility class
    }

    static String generate(PanelExportConfig config) {
        var sb = new StringBuilder();

        appendLine(sb, "/**");
        appendLine(sb, " * Panel / Montage Export -- configuration record");
        appendLine(sb, " * Generated by QuIET (QuPath Image Export Toolkit)");
        appendLine(sb, " *");
        appendLine(sb, " * A panel export applies one single-image export recipe to every");
        appendLine(sb, " * selected image and composes the results into one rows-by-columns");
        appendLine(sb, " * figure. Panel composition is performed by QuIET's Panel / Montage");
        appendLine(sb, " * export mode -- re-run it from the QuIET wizard with the settings");
        appendLine(sb, " * below.");
        appendLine(sb, " *");
        appendLine(sb, " * Conventions follow ImageJ 'Make Montage', BioVoxxel Figure Tools");
        appendLine(sb, " * and QuickFigures.");
        appendLine(sb, " */");
        appendLine(sb, "");

        appendLine(sb, "// ========== PANEL CONFIGURATION ==========");
        appendLine(sb, "def recipeCategory = " + quote(config.getRecipeCategory().name()));
        appendRecipeSettings(sb, config);
        appendLine(sb, "def gridRows = " + config.getRows());
        appendLine(sb, "def gridColumns = " + config.getCols());
        appendLine(sb, "def gutterX = " + config.getGutterX() + "  // pixels");
        appendLine(sb, "def gutterY = " + config.getGutterY() + "  // pixels");
        appendLine(sb, "def backgroundColor = " + quote(toHex(config.getBackgroundColor())));
        appendLine(sb, "def cellFitMode = " + quote(config.getCellFitMode().name()));
        appendLine(sb, "def outputFormat = " + quote(config.getFormat().name()));
        appendLine(sb, "def outputFile = " + quote(
                new java.io.File(config.getOutputDirectory(),
                        config.buildOutputFilename()).getAbsolutePath()));
        appendLine(sb, "");

        appendLine(sb, "// ---------- Captions ----------");
        appendLine(sb, "def showFilenameCaption = " + config.isShowFilenameCaption());
        appendLine(sb, "def captionPosition = " + quote(config.getCaptionPosition().name()));
        var fields = config.getMetadataFields();
        var fieldStr = new StringBuilder("def captionMetadataFields = [");
        for (int i = 0; i < fields.size(); i++) {
            if (i > 0) {
                fieldStr.append(", ");
            }
            fieldStr.append(quote(fields.get(i)));
        }
        fieldStr.append("]");
        appendLine(sb, fieldStr.toString());
        appendLine(sb, "def captionFontSize = " + config.getCaptionFontSize());
        appendLine(sb, "def captionColor = " + quote(toHex(config.getCaptionColor())));
        appendLine(sb, "// =========================================");
        appendLine(sb, "");

        appendLine(sb, "println 'Panel / Montage export configuration'");
        appendLine(sb, "println \"  Recipe category : ${recipeCategory}\"");
        appendLine(sb, "println \"  Grid            : ${gridRows} rows x ${gridColumns} columns\"");
        appendLine(sb, "println \"  Gutters         : ${gutterX} x ${gutterY} px\"");
        appendLine(sb, "println \"  Cell fit        : ${cellFitMode}\"");
        appendLine(sb, "println \"  Output          : ${outputFile} (${outputFormat})\"");
        appendLine(sb, "println ''");
        appendLine(sb, "println 'To produce this figure, open the QuIET export wizard,'");
        appendLine(sb, "println 'choose Panel / Montage, and apply the settings above.'");
        appendLine(sb, "println 'The composed figure is written next to a'");
        appendLine(sb, "println 'panel_figure_info.txt provenance sidecar that lists the'");
        appendLine(sb, "println 'exact source images and recipe used.'");

        return sb.toString();
    }

    /**
     * Append the recipe's own per-cell settings as comment lines, so the
     * configuration record documents how each panel was rendered -- not only
     * the montage layout. The full settings also live in the JSON recipe and
     * the panel_figure_info.txt sidecar.
     */
    private static void appendRecipeSettings(StringBuilder sb, PanelExportConfig config) {
        Object recipe = config.getRecipeConfig();
        appendLine(sb, "// Recipe (per-cell render settings):");
        if (recipe instanceof RenderedExportConfig rc) {
            appendLine(sb, "//   render mode = " + rc.getRenderMode().name());
            appendLine(sb, "//   downsample  = " + rc.getDownsample());
            if (rc.getTargetDpi() > 0) {
                appendLine(sb, "//   target DPI  = " + rc.getTargetDpi());
            }
            appendLine(sb, "//   display     = " + rc.getDisplaySettingsMode().name());
        } else if (recipe instanceof RawExportConfig raw) {
            appendLine(sb, "//   region type = " + raw.getRegionType().name());
            appendLine(sb, "//   downsample  = " + raw.getDownsample());
        } else if (recipe instanceof MaskExportConfig mc) {
            appendLine(sb, "//   mask type   = " + mc.getMaskType().name());
            appendLine(sb, "//   object src  = " + mc.getObjectSource().name());
            appendLine(sb, "//   downsample  = " + mc.getDownsample());
        } else if (recipe instanceof ObjectCropConfig occ) {
            appendLine(sb, "//   object type = " + occ.getObjectType().name());
            appendLine(sb, "//   crop size   = " + occ.getCropSize() + " px");
            appendLine(sb, "//   downsample  = " + occ.getDownsample());
        }
    }

    /**
     * Convert an AWT colour to a {@code #RRGGBB} hex string.
     */
    private static String toHex(Color c) {
        if (c == null) {
            return "#FFFFFF";
        }
        return String.format("#%02X%02X%02X", c.getRed(), c.getGreen(), c.getBlue());
    }
}
