package qupath.ext.quiet.export;

import qupath.ext.quiet.export.OutputFormat;
import qupath.ext.quiet.export.RawExportConfig;

import static qupath.ext.quiet.export.ScriptGenerator.appendLine;
import static qupath.ext.quiet.export.ScriptGenerator.quote;

/**
 * Generates self-contained Groovy scripts for raw pixel data export.
 */
class RawScriptGenerator {

    private RawScriptGenerator() {
        // Utility class
    }

    static String generate(RawExportConfig config) {
        var sb = new StringBuilder();

        appendLine(sb, "/**");
        appendLine(sb, " * Raw Image Data Export Script");
        appendLine(sb, " * Generated by QuIET (QuPath Image Export Toolkit)");
        appendLine(sb, " *");
        appendLine(sb, " * Exports raw pixel data from project images.");
        appendLine(sb, " * Region type: " + config.getRegionType().name());
        if (config.getSelectedChannels() != null) {
            appendLine(sb, " * Channels: " + config.getSelectedChannels());
        }
        if (config.getFormat() == OutputFormat.OME_TIFF_PYRAMID) {
            appendLine(sb, " * Output: OME-TIFF Pyramid (" + config.getPyramidLevels() + " levels)");
        }
        appendLine(sb, " *");
        appendLine(sb, " * Parameters below can be modified before re-running.");
        appendLine(sb, " */");
        appendLine(sb, "");

        // Imports
        appendLine(sb, "import qupath.lib.images.writers.ImageWriterTools");
        appendLine(sb, "import qupath.lib.regions.RegionRequest");
        if (config.getSelectedChannels() != null) {
            appendLine(sb, "import qupath.lib.images.servers.TransformedServerBuilder");
        }
        if (config.getFormat() == OutputFormat.OME_TIFF_PYRAMID) {
            appendLine(sb, "import qupath.lib.images.writers.ome.OMEPyramidWriter");
        }
        appendLine(sb, "");

        // Configuration parameters
        appendLine(sb, "// ========== CONFIGURATION (modify as needed) ==========");
        appendLine(sb, "def regionType = " + quote(config.getRegionType().name()));
        appendLine(sb, "def downsample = " + config.getDownsample());
        appendLine(sb, "def outputFormat = " + quote(config.getFormat().getExtension()));
        appendLine(sb, "def outputDir = " + quote(config.getOutputDirectory().getAbsolutePath()));

        // Padding config
        boolean isAnnotation = config.getRegionType() != RawExportConfig.RegionType.WHOLE_IMAGE;
        if (isAnnotation && config.getPaddingPixels() > 0) {
            appendLine(sb, "def paddingPixels = " + config.getPaddingPixels());
        }

        // Channel config
        if (config.getSelectedChannels() != null) {
            var channels = config.getSelectedChannels();
            var channelStr = new StringBuilder("def selectedChannels = [");
            for (int i = 0; i < channels.size(); i++) {
                if (i > 0) channelStr.append(", ");
                channelStr.append(channels.get(i));
            }
            channelStr.append("]");
            appendLine(sb, channelStr.toString());
        }

        // Pyramid config
        if (config.getFormat() == OutputFormat.OME_TIFF_PYRAMID) {
            appendLine(sb, "def pyramidLevels = " + config.getPyramidLevels());
            appendLine(sb, "def tileSize = " + config.getTileSize());
            if (config.getCompressionType() != null) {
                appendLine(sb, "def compressionType = " + quote(config.getCompressionType()));
            }
        }

        appendLine(sb, "// =======================================================");
        appendLine(sb, "");

        // Project loading
        appendLine(sb, "def project = getProject()");
        appendLine(sb, "if (project == null) {");
        appendLine(sb, "    println 'ERROR: No project is open'");
        appendLine(sb, "    return");
        appendLine(sb, "}");
        appendLine(sb, "");

        // Output directory
        appendLine(sb, "def outDir = new File(outputDir)");
        appendLine(sb, "outDir.mkdirs()");
        appendLine(sb, "");

        // Main processing loop
        appendLine(sb, "def entries = project.getImageList()");
        appendLine(sb, "println \"Processing ${entries.size()} images...\"");
        appendLine(sb, "");
        appendLine(sb, "int succeeded = 0");
        appendLine(sb, "int failed = 0");
        appendLine(sb, "");
        appendLine(sb, "for (int i = 0; i < entries.size(); i++) {");
        appendLine(sb, "    def entry = entries[i]");
        appendLine(sb, "    def imageName = entry.getImageName()");
        appendLine(sb, "    def entryName = imageName");
        appendLine(sb, "    println \"[${i + 1}/${entries.size()}] Processing: ${entryName}\"");
        appendLine(sb, "");
        appendLine(sb, "    try {");
        appendLine(sb, "        def imageData = entry.readImageData()");
        appendLine(sb, "        def server = imageData.getServer()");
        appendLine(sb, "");

        // Channel extraction
        if (config.getSelectedChannels() != null) {
            appendLine(sb, "        // Extract selected channels");
            appendLine(sb, "        def exportServer = new TransformedServerBuilder(server)");
            appendLine(sb, "                .extractChannels(selectedChannels as int[])");
            appendLine(sb, "                .build()");
            appendLine(sb, "");
        } else {
            appendLine(sb, "        def exportServer = server");
            appendLine(sb, "");
        }

        if (config.getRegionType() == RawExportConfig.RegionType.WHOLE_IMAGE) {
            generateWholeImageExport(sb, config);
        } else {
            generateAnnotationExport(sb, config);
        }

        appendLine(sb, "");
        if (config.getSelectedChannels() != null) {
            appendLine(sb, "        if (exportServer != server) exportServer.close()");
        }
        appendLine(sb, "        server.close()");
        appendLine(sb, "");
        appendLine(sb, "    } catch (Exception e) {");
        appendLine(sb, "        println \"  FAIL: ${e.getMessage()}\"");
        appendLine(sb, "        failed++");
        appendLine(sb, "    }");
        appendLine(sb, "}");
        appendLine(sb, "");
        appendLine(sb, "println ''");
        appendLine(sb, "println \"Export complete: ${succeeded} succeeded, ${failed} failed\"");

        return sb.toString();
    }

    private static void generateWholeImageExport(StringBuilder sb, RawExportConfig config) {
        if (config.getFormat() == OutputFormat.OME_TIFF_PYRAMID) {
            // OME Pyramid export
            appendLine(sb, "        def sanitized = qupath.lib.common.GeneralTools.stripInvalidFilenameChars(entryName)");
            appendLine(sb, "        if (sanitized == null || sanitized.isBlank()) sanitized = 'unnamed'");
            appendLine(sb, "        def outputPath = new File(outDir, sanitized + '.' + outputFormat).getAbsolutePath()");
            appendLine(sb, "");
            appendLine(sb, "        def pyramidBuilder = new OMEPyramidWriter.Builder(exportServer)");
            appendLine(sb, "                .scaledDownsampling(downsample, pyramidLevels)");
            appendLine(sb, "                .tileSize(tileSize)");
            appendLine(sb, "                .parallelize()");
            if (config.getCompressionType() != null) {
                appendLine(sb, "        pyramidBuilder.compression(OMEPyramidWriter.CompressionType.valueOf(compressionType))");
            }
            appendLine(sb, "        pyramidBuilder.writePyramid(outputPath)");
            appendLine(sb, "        println \"  OK: ${outputPath}\"");
            appendLine(sb, "        succeeded++");
        } else {
            // Standard export
            appendLine(sb, "        def request = RegionRequest.createInstance(");
            appendLine(sb, "                exportServer.getPath(), downsample,");
            appendLine(sb, "                0, 0, exportServer.getWidth(), exportServer.getHeight())");
            appendLine(sb, "        def image = exportServer.readRegion(request)");
            appendLine(sb, "");
            appendLine(sb, "        def sanitized = qupath.lib.common.GeneralTools.stripInvalidFilenameChars(entryName)");
            appendLine(sb, "        if (sanitized == null || sanitized.isBlank()) sanitized = 'unnamed'");
            appendLine(sb, "        def outputPath = new File(outDir, sanitized + '.' + outputFormat).getAbsolutePath()");
            appendLine(sb, "        ImageWriterTools.writeImage(image, outputPath)");
            appendLine(sb, "        println \"  OK: ${outputPath}\"");
            appendLine(sb, "        succeeded++");
        }
    }

    private static void generateAnnotationExport(StringBuilder sb, RawExportConfig config) {
        boolean selectedOnly = config.getRegionType() == RawExportConfig.RegionType.SELECTED_ANNOTATIONS;
        if (selectedOnly) {
            appendLine(sb, "        def annotations = imageData.getHierarchy().getSelectionModel()");
            appendLine(sb, "                .getSelectedObjects().findAll { it.isAnnotation() }");
        } else {
            appendLine(sb, "        def annotations = imageData.getHierarchy().getAnnotationObjects()");
        }
        appendLine(sb, "");
        appendLine(sb, "        if (annotations.isEmpty()) {");
        appendLine(sb, "            println \"  SKIP: No annotations found\"");
        if (config.getSelectedChannels() != null) {
            appendLine(sb, "            if (exportServer != server) exportServer.close()");
        }
        appendLine(sb, "            server.close()");
        appendLine(sb, "            continue");
        appendLine(sb, "        }");
        appendLine(sb, "");
        appendLine(sb, "        int regionIndex = 0");
        appendLine(sb, "        annotations.each { annotation ->");
        appendLine(sb, "            def roi = annotation.getROI()");
        appendLine(sb, "            if (roi == null) return");
        appendLine(sb, "");
        appendLine(sb, "            int x = (int) roi.getBoundsX()");
        appendLine(sb, "            int y = (int) roi.getBoundsY()");
        appendLine(sb, "            int w = (int) Math.ceil(roi.getBoundsWidth())");
        appendLine(sb, "            int h = (int) Math.ceil(roi.getBoundsHeight())");

        // Padding
        if (config.getPaddingPixels() > 0) {
            appendLine(sb, "");
            appendLine(sb, "            // Apply padding");
            appendLine(sb, "            x -= paddingPixels");
            appendLine(sb, "            y -= paddingPixels");
            appendLine(sb, "            w += 2 * paddingPixels");
            appendLine(sb, "            h += 2 * paddingPixels");
        }

        appendLine(sb, "");
        appendLine(sb, "            // Clamp to image bounds");
        appendLine(sb, "            x = Math.max(0, x)");
        appendLine(sb, "            y = Math.max(0, y)");
        appendLine(sb, "            w = Math.min(w, exportServer.getWidth() - x)");
        appendLine(sb, "            h = Math.min(h, exportServer.getHeight() - y)");
        appendLine(sb, "            if (w <= 0 || h <= 0) return");
        appendLine(sb, "");
        appendLine(sb, "            def request = RegionRequest.createInstance(");
        appendLine(sb, "                    exportServer.getPath(), downsample, x, y, w, h)");
        appendLine(sb, "            def regionImage = exportServer.readRegion(request)");
        appendLine(sb, "");
        appendLine(sb, "            def sanitized = qupath.lib.common.GeneralTools.stripInvalidFilenameChars(entryName)");
        appendLine(sb, "            if (sanitized == null || sanitized.isBlank()) sanitized = 'unnamed'");
        appendLine(sb, "            def outputPath = new File(outDir, sanitized + \"_region_${regionIndex}.\" + outputFormat).getAbsolutePath()");
        appendLine(sb, "            ImageWriterTools.writeImage(regionImage, outputPath)");
        appendLine(sb, "            println \"  OK: ${outputPath}\"");
        appendLine(sb, "            regionIndex++");
        appendLine(sb, "        }");
        appendLine(sb, "        succeeded++");
    }
}
